import type {
  RealmId,
  RealmDefinition,
  ContentRating,
  ContentRatingDefinition,
  LocaleId,
} from "../types/index.js";

export * from "./credits.js";
export * from "./chuzi-ai-prompts.js";

export const REALM_IDS: readonly RealmId[] = ["cosmos", "wilds"] as const;

export const SUPPORTED_LOCALES: readonly LocaleId[] = [
  "en",
  "es",
  "fr",
  "de",
  "pt",
] as const;

export const LOCALE_LABELS: Record<LocaleId, string> = {
  en: "English",
  es: "Español",
  fr: "Français",
  de: "Deutsch",
  pt: "Português",
};

export const DEFAULT_LOCALE: LocaleId = "en";

type RealmLexiconOverrides = Partial<Record<RealmId, Record<string, string>>>;
let runtimeRealmLexiconOverrides: RealmLexiconOverrides = {};

export function getRealmLexiconOverrides(): RealmLexiconOverrides {
  return {
    cosmos: runtimeRealmLexiconOverrides.cosmos
      ? { ...runtimeRealmLexiconOverrides.cosmos }
      : undefined,
    wilds: runtimeRealmLexiconOverrides.wilds
      ? { ...runtimeRealmLexiconOverrides.wilds }
      : undefined,
  };
}

export function setRealmLexiconOverrides(overrides: RealmLexiconOverrides): void {
  runtimeRealmLexiconOverrides = {
    cosmos: overrides.cosmos ? { ...overrides.cosmos } : undefined,
    wilds: overrides.wilds ? { ...overrides.wilds } : undefined,
  };
}

export function isSupportedLocale(value: unknown): value is LocaleId {
  return (
    typeof value === "string" &&
    SUPPORTED_LOCALES.includes(value as LocaleId)
  );
}

/**
 * Normalize a raw locale tag (e.g. "en-US", "pt_BR") to a supported LocaleId,
 * matching the PHP `LocaleResolver::normalize` behavior.
 */
export function normalizeLocale(value: string | null | undefined): LocaleId | null {
  if (!value) return null;
  const lower = value.toLowerCase().trim();
  if (isSupportedLocale(lower)) return lower;
  const base = lower.split(/[-_]/, 1)[0];
  return isSupportedLocale(base) ? base : null;
}

/**
 * Pick the best supported locale from a browser Accept-Language string.
 * Mirrors PHP `LocaleResolver::matchAcceptLanguage` (q-value aware).
 */
export function matchAcceptLanguage(
  accept: string | null | undefined
): LocaleId | null {
  if (!accept) return null;
  const tags = accept
    .split(",")
    .map((part) => {
      const [tag, ...params] = part.trim().split(";");
      const qParam = params.find((p) => p.trim().startsWith("q="));
      const q = qParam ? parseFloat(qParam.split("=")[1]) || 0 : 1;
      return { tag: tag.trim(), q };
    })
    .filter((c) => c.tag && c.tag !== "*")
    .sort((a, b) => b.q - a.q);

  for (const c of tags) {
    const normalized = normalizeLocale(c.tag);
    if (normalized) return normalized;
  }
  return null;
}

export const CONTENT_RATING_IDS: readonly ContentRating[] = [
  "G",
  "PG",
  "PG-13",
  "R",
  "NC-17",
] as const;

export const CONTENT_RATINGS: Record<ContentRating, ContentRatingDefinition> = {
  G: {
    id: "G",
    label: "G",
    description: "General Audiences — all ages admitted.",
  },
  PG: {
    id: "PG",
    label: "PG",
    description: "Parental Guidance Suggested — some material may not be suitable for children.",
  },
  "PG-13": {
    id: "PG-13",
    label: "PG-13",
    description: "Parents Strongly Cautioned — some material may be inappropriate for children under 13.",
  },
  R: {
    id: "R",
    label: "R",
    description: "Restricted — under 17 requires accompanying parent or adult guardian.",
  },
  "NC-17": {
    id: "NC-17",
    label: "NC-17",
    description: "Adults Only — no one 17 and under admitted.",
  },
};

export function isContentRating(value: unknown): value is ContentRating {
  return typeof value === "string" && CONTENT_RATING_IDS.includes(value as ContentRating);
}

export const REALMS: Record<RealmId, RealmDefinition> = {
  cosmos: {
    label: "CHUZI COSMOS",
    short_label: "Cosmos",
    lexicon: {
      genre: "Galaxy",
      story: "Star System",
      scene: "Planet",
      scene_choice: "Trajectory",
      node: "Signal",
      node_type_choice: "Trajectory",
      node_type_media: "Transmission",
      node_type_go_to_scene: "Warp",
      player: "Voyager",
      library: "Star Chart",
      library_open: "Open Star Chart",
      library_close: "Close Star Chart",
      editor: "Mission Control",
      publish: "Launch",
      experience_realm_idea: "Outer Space",
      the_end: "The End",
      media_pool: "Cargo Bay",
      scene_graph: "Star Chart",
      watch_path: "Your trajectory",
      untitled_story: "Untitled Star System",
      unknown_genre: "Unknown Galaxy",
      scenes_count: "planets",
      choices_count: "trajectories",
      drafts_published: "Drafts + Launched",
      published_ver: "Launched ver.",
      draft: "Draft",
      no_scenes_yet: "No planets in this chart yet.",
      no_path_yet: "No trajectory to show yet.",
      menu_empty_drafts: "No star systems yet. Chart one to begin.",
      menu_empty_published: "No launched systems in the chart.",
      menu_published_heading: "Launched constellations",
      menu_create_story: "New star system",
      menu_create_film: "Create film",
      film_title_placeholder: "Star system title",
      select_genre: "Select galaxy",
      genre_field_aria: "Galaxy",
      delete_story_verb: "Delete star system",
      title_scene_default: "Launch",
      choices_made_stat: "trajectories taken",
      content_rating: "Audience Class",
      content_rating_field_aria: "Audience class",
      select_content_rating: "Select audience class",
      unrated: "Unclassified",
      viewer_credits: "Fuel Cells",
      creator_credits: "Stardust",
      editor_media_upload: "Upload Transmission",
      editor_media_preview: "Transmission Preview",
      editor_alt_media: "Effects",
      editor_choices: "Choices",
      editor_scene_settings: "Star Settings",
      editor_title_scene: "Start",
      editor_film_title: "Star System Title",
      editor_film_title_hint: "Click to rename this star system",
      editor_ending_scene: "End",
      editor_play: "Engage",
      editor_pause: "Hold",
      editor_prev_frame: "Previous Frame",
      editor_next_frame: "Next Frame",
      editor_seek: "Seek",
      editor_no_media: "No transmission assigned",
      editor_uploading: "Transmitting\u2026",
      editor_drop_media: "Drop transmission here",
      editor_scene_type: "Star Type",
      editor_save: "Lock In",
      editor_cancel: "Abort",
      editor_create_scene: "Chart Planet",
      editor_create_scene_plain: "Create New Scene",
      editor_create_scene_cost: "1 Stardust",
      editor_delete_scene_cta: "Delete Scene",
      editor_delete_scene_confirm: "Click again to confirm",
      editor_scene_locked_delete: "Start and end scenes cannot be deleted.",
      editor_scene_color: "Star Hue",
      chuzi_ai_name: "Chuzi AI",
      chuzi_ai_create_with: "Create with Chuzi AI",
      chuzi_ai_create_manual: "Enter title manually",
      chuzi_ai_intro: "Answer story-circle prompts and Chuzi AI will chart your short story.",
      chuzi_ai_step_of: "Step",
      chuzi_ai_back: "Back",
      chuzi_ai_next: "Next",
      chuzi_ai_scenes_label: "scenes",
      chuzi_ai_creating: "Creating\u2026",
      chuzi_ai_generate_failed: "Story generation failed.",
      chuzi_ai_build_failed: "Failed to build story.",
      chuzi_ai_generate: "Generate story",
      chuzi_ai_generating: "Generating\u2026",
      chuzi_ai_token_in: "Tokens in",
      chuzi_ai_token_out: "Tokens out",
      chuzi_ai_credits_cost: "AI credits",
      chuzi_ai_scene_credits: "Scene credits",
      chuzi_ai_total_cost: "Total create credits",
      chuzi_ai_insufficient: "Not enough create credits for this generation.",
      chuzi_ai_apply: "Build story",
      chuzi_ai_applying: "Building scenes\u2026",
      chuzi_ai_step_hero: "Hero",
      chuzi_ai_step_hero_hint: "Who is your protagonist? Name, age, personality, and what makes them relatable.",
      chuzi_ai_step_world: "Ordinary world",
      chuzi_ai_step_world_hint: "Where does the story begin? Describe the setting and daily life before adventure calls.",
      chuzi_ai_step_you: "You",
      chuzi_ai_step_you_hint: "The character in a zone of comfort. What is their normal life like right now?",
      chuzi_ai_step_need: "Need",
      chuzi_ai_step_need_hint: "Something isn\u2019t right. What problem, longing, or imbalance disrupts their comfort?",
      chuzi_ai_step_go: "Go",
      chuzi_ai_step_go_hint: "Crossing the threshold. What event pushes them into the unknown?",
      chuzi_ai_step_search: "Search",
      chuzi_ai_step_search_hint: "Trials, growth, and exploration. What challenges and discoveries shape them?",
      chuzi_ai_step_find: "Find",
      chuzi_ai_step_find_hint: "The thing is found or revealed. What truth, object, or insight do they uncover?",
      chuzi_ai_step_take: "Take",
      chuzi_ai_step_take_hint: "Pay the price. What must they sacrifice or confront to claim their goal?",
      chuzi_ai_step_return: "Return",
      chuzi_ai_step_return_hint: "Back to the known world. How do they bring what they learned home?",
      chuzi_ai_step_change: "Change",
      chuzi_ai_step_change_hint: "Transformation achieved. How is the hero different from who they were at the start?",
      chuzi_ai_step_tone: "Tone & mood",
      chuzi_ai_step_tone_hint: "Genre, mood, and atmosphere (e.g. bittersweet sci-fi, cozy mystery, epic fantasy).",
      chuzi_ai_monomyth_hero: "Hero\u2019s Journey: the protagonist",
      chuzi_ai_monomyth_world: "Monomyth: ordinary world",
      chuzi_ai_monomyth_you: "Story Circle: zone of comfort",
      chuzi_ai_monomyth_need: "Story Circle: something isn\u2019t right",
      chuzi_ai_monomyth_go: "Monomyth: crossing the first threshold",
      chuzi_ai_monomyth_search: "Monomyth: road of trials",
      chuzi_ai_monomyth_find: "Monomyth: the ultimate boon",
      chuzi_ai_monomyth_take: "Monomyth: atonement with the father",
      chuzi_ai_monomyth_return: "Monomyth: crossing the return threshold",
      chuzi_ai_monomyth_change: "Monomyth: freedom to live",
      editor_ai_generate: "Generate Transmission",
      editor_ai_generating: "Transmitting Signal\u2026",
      editor_ai_mood_question: "What energy should this planet radiate?",
      editor_ai_style_question: "What vision style for this transmission?",
      editor_ai_prompt_question: "Describe this planet\u2019s landscape",
      editor_ai_accept: "Lock Transmission",
      editor_ai_reject: "Reject Signal",
      editor_ai_retry: "Retransmit",
      editor_ai_feedback_prompt: "How should we adjust the signal?",
      editor_ai_credit_cost: "1 Stardust per signal",
      spending_modal_title: "Refuel Your Mission",
      spending_modal_body: "You need more credits to continue. Choose how many to add.",
      spending_modal_no_payment: "Add a payment method to purchase credits.",
      spending_modal_credits_label: "Credits to add",
      spending_modal_price_label: "Total",
      spending_modal_admin_note: "Admin — credits are granted free of charge.",
      spending_modal_purchase: "Purchase Credits",
      spending_modal_grant: "Grant Credits",
      spending_modal_add_card: "Add Payment Method",
      spending_modal_card_last_four: "Card last four digits",
      spending_modal_card_label: "Card label (optional)",
      spending_modal_processing: "Processing\u2026",
      spending_modal_success: "Credits added.",
      spending_modal_error: "Could not complete purchase. Try again.",
      spending_modal_cancel: "Not now",
      spending_insufficient_credits: "Not enough credits. Purchase more to continue.",
      editor_ai_generating_scene: "Planet forming\u2026",
      editor_ai_style_badge: "Signal Style",
      editor_ai_failed: "Signal lost. Try retransmitting.",
      editor_media_attached: "This star already has a transmission locked in.",
      editor_remove_media: "Remove Transmission",
      editor_media_question: "What's this scene's media?",
      editor_media_type_text: "Text",
      editor_media_type_imagery: "Imagery",
      editor_media_type_film: "Film",
      editor_media_preview_cta: "Preview",
      editor_media_preview_disabled: "Add text to enable preview.",
      editor_text_toolbar_label: "Generator",
      editor_text_font_label: "Font",
      editor_text_color_label: "Text Color",
      editor_text_background_label: "Background",
      editor_text_placeholder: "Start writing scene media...",
      editor_line_add: "Add Text",
      editor_text_lines_section: "Transmission Lines",
      editor_line_editor_label: "Editor",
      editor_line_number: "Line",
      editor_select_line_hint: "Select a transmission line to edit",
      editor_select_effect_hint: "Select an effect to edit",
      editor_select_choice_hint: "Select a choice to edit",
      editor_line_timestamp: "Appears at",
      editor_line_fade_in: "Fade In",
      editor_line_fade_out: "Fade Out",
      editor_line_duration: "Duration",
      editor_line_persist: "Stay on Screen",
      editor_effects_section: "Effects",
      editor_effects_add: "Add sounds, effects, etc",
      editor_effect_fade_in_sound: "Fade In Sound",
      editor_effect_fade_out_sound: "Fade Out Sound",
      editor_effect_fade_in_visual: "Fade In",
      editor_effect_fade_out_visual: "Fade Out",
      editor_timeline_label: "Timeline",
      editor_preview_label: "Preview",
      editor_preview_play: "Play",
      editor_preview_pause: "Pause",
      editor_media_placeholder_imagery: "Imagery authoring is coming soon.",
      editor_media_placeholder_film: "Film authoring is coming soon.",
      editor_goto_scene: "Goto Star",
      editor_scene_duration: "Transmission Duration",
      editor_add_choice: "Add Trajectory",
      editor_arrow_tool: "Place Arrow",
      editor_goto_nullified: "Disabled — trajectories override goto",
      editor_remove_choice: "Remove Trajectory",
      editor_choice_target: "Destination Star",
      editor_choices_empty_hint: "Set a goto star or add a trajectory to branch the story.",
      editor_goto_none: "None",
      editor_choice_label: "Trajectory",
      editor_flow_timeline: "Story Flow",
      editor_flow_goto_path: "Default Goto",
      editor_flow_add_choice_here: "Add Trajectory Here",
      editor_flow_choice_branch: "Branch",
      editor_flow_content_ref: "Content",
      editor_scene_duration_unit: "seconds",
      editor_scene_duration_override_hint: "Overrides transmission length. Signal runtime: {duration}s",
      editor_arrow_scale: "Span",
      editor_arrow_rotation: "Bearing",
      editor_arrow_rotate_hint: "Drag the beacon above the arrow in preview to rotate",
      constellation_no_coverbox: "Uncharted",
      hud_edit_control: "Engage",
      hud_delete_control: "Jettison",
      hud_publish_control: "Launch",
      hud_launch_control: "Launch",
      editor_publish_story: "Release",
      viewer_loading: "Loading transmission…",
      viewer_preparing: "Spooling media…",
      viewer_close: "Exit",
      viewer_complete: "Transmission complete",
      viewer_stage_label: "Viewport",
      viewer_choose_path: "Choose",
      create_button: "CREATE",
      publish_form_heading: "Launch readiness",
      tags_label: "Signal Tags",
      tags_placeholder: "Search signal tags\u2026",
      tags_empty: "No signal tags yet",
      tags_required: "At least one signal tag is required.",
      story_picker_label: "Constellations",
      created_by: "Directed by",
      chosen_by: "Chosen by",
      story_metadata_heading: "Star system details",
      story_metadata_save: "Save",
      constellation_title_edit_hint: "Edit star system title and details",
      director_profile_title: "Director profile",
      director_profile_name_label: "Name",
      director_profile_realm_label: "Experience realm",
      director_profile_image_label: "Image",
      director_profile_image_hint:
        "Realm-themed seal — switching the realm above swaps the seal. Custom uploads land with the V1 avatar endpoints.",
      director_profile_tab_profile: "Profile",
      director_profile_tab_experience_mapping: "Experience Mapping",
      director_profile_admin_only: "Admin only",
      director_profile_cancel: "Cancel",
      director_profile_close: "Close",
      director_profile_save: "Save",
      director_profile_saving: "Saving…",
      director_profile_name_required: "Name is required.",
      director_profile_save_failed: "Save failed",
      experience_mapping_loading: "Loading experience mapping…",
      experience_mapping_empty: "No template hierarchy available yet.",
      experience_mapping_retry: "Retry",
      experience_mapping_story_label: "Story",
      experience_mapping_scene_label: "Scene",
      experience_mapping_action_label: "Action",
      experience_mapping_field_title: "Title",
      experience_mapping_field_description: "Description",
      experience_mapping_field_genre: "Genre",
      experience_mapping_field_content_rating: "Content rating",
      experience_mapping_field_color: "Color",
      experience_mapping_field_name: "Name",
      experience_mapping_field_type: "Type",
      experience_mapping_field_order: "Order",
      experience_mapping_field_duration: "Duration",
      experience_mapping_field_properties: "Properties",
      experience_mapping_field_subproperties: "Subproperties",
      experience_mapping_save_changes: "Save changes",
      experience_mapping_saved: "Saved",
      experience_mapping_save_error: "Could not save changes.",
      experience_mapping_delete_story: "Delete story",
      experience_mapping_delete_scene: "Delete scene",
      experience_mapping_delete_action: "Delete action",
      experience_mapping_delete_confirm: "Click again to confirm",
      experience_mapping_delete_error: "Delete failed.",
      experience_mapping_expand_all: "Expand all",
      experience_mapping_collapse_all: "Collapse all",
      experience_mapping_forbidden: "You do not have admin access for this section.",
      experience_mapping_bad_json: "JSON must be valid before saving.",
      experience_mapping_intro:
        "Edit realm vocabulary from largest to smallest. Generate JSON and paste it in chat for code application.",
      experience_mapping_dirty: "dirty changes",
      experience_mapping_export_ready: "No unsaved mapping edits yet.",
      experience_mapping_export_json: "Generate JSON export",
      experience_mapping_copy_json: "Copy JSON",
      experience_mapping_copied: "Copied",
      experience_mapping_paste_instruction:
        "Paste this JSON in chat and I will apply it to chuzi-shared.",
      experience_mapping_export_empty: "Export output appears here.",
      experience_mapping_select_realm: "Select realm",
      experience_mapping_group_major_idea: "Major Idea",
      experience_mapping_helper_realm_idea:
        "Highest-level concept for this realm.",
      experience_mapping_save_experience: "Save to experience",
      experience_mapping_saved_experience:
        "Saved to current experience. Some labels appear immediately.",
      auth_email_placeholder: "Email",
      auth_password_input_placeholder: "Password",
      auth_password_sign_in_button: "Sign In",
      auth_password_signing_in: "Signing in...",
      auth_signin_tab: "Sign in",
      auth_signup_tab: "Sign up",
      auth_signup_subtitle: "Create your account with secure sign-in.",
      auth_signin_subtitle: "Sign in with your account provider.",
      auth_sign_up_button: "Continue with Google",
      auth_username_placeholder: "Username",
      auth_sign_in_button: "Continue with Google",
      auth_signing_in: "Signing in...",
      auth_oidc_redirecting: "Redirecting to secure sign-in...",
      auth_oidc_failed: "Could not start sign-in.",
      auth_oidc_callback_processing: "Completing sign-in...",
      auth_oidc_verified: "Signed in. Redirecting...",
      auth_oidc_callback_failed: "Could not complete sign-in.",
      auth_oidc_token_missing: "Sign-in token was missing.",
      auth_magic_link_sent:
        "If that email is registered, a magic link has been sent.",
      auth_magic_link_sent_signup: "Check your email for your sign-up link.",
      auth_magic_link_verifying: "Verifying magic link...",
      auth_magic_link_verified: "Signed in. Redirecting...",
      auth_magic_link_failed: "This magic link is invalid or expired.",
      auth_magic_link_cta: "Use another email",
      auth_login_failed: "Sign-in failed.",
      auth_username_checking: "Checking username availability...",
      auth_username_available: "Username is available.",
      auth_username_unavailable: "Username is taken; updated to an available suggestion.",
      auth_username_required: "Username is required.",
      auth_username_update_failed: "Could not reserve a unique username.",
      experience_mapping_group_experience_root: "Experience Root",
      experience_mapping_group_node_types: "Node Types",
      experience_mapping_group_scene_structure: "Scene Structure",
      experience_mapping_group_media: "Media Terms",
      experience_mapping_group_counts: "Counts and Adjacent Labels",
      experience_mapping_helper_story: "Largest narrative unit.",
      experience_mapping_helper_scene: "Contained unit under story.",
      experience_mapping_helper_scene_choice: "Branching choice in a scene.",
      experience_mapping_helper_node: "Smallest flow node.",
      experience_mapping_helper_alt_media: "Smallest related media label.",
    },
    locales: {
      es: {
        genre: "Galaxia",
        story: "Sistema Estelar",
        scene: "Planeta",
        scene_choice: "Trayectoria",
        player: "Viajero",
        library: "Carta Estelar",
        editor: "Control de Misión",
        publish: "Lanzar",
        the_end: "Órbita Final",
        untitled_story: "Sistema Estelar sin título",
        menu_create_story: "Nuevo sistema estelar",
        film_title_placeholder: "Título del sistema estelar",
        select_genre: "Seleccionar galaxia",
        created_by: "Dirigido por",
      },
      fr: {
        genre: "Galaxie",
        story: "Système Stellaire",
        scene: "Planète",
        scene_choice: "Trajectoire",
        player: "Voyageur",
        library: "Carte Stellaire",
        editor: "Contrôle de Mission",
        publish: "Lancer",
        the_end: "Orbite Finale",
        untitled_story: "Système stellaire sans titre",
        menu_create_story: "Nouveau système stellaire",
        film_title_placeholder: "Titre du système stellaire",
        select_genre: "Sélectionner une galaxie",
        created_by: "Réalisé par",
      },
      de: {
        genre: "Galaxie",
        story: "Sternsystem",
        scene: "Planet",
        player: "Reisender",
        publish: "Starten",
      },
      pt: {
        genre: "Galáxia",
        story: "Sistema Estelar",
        scene: "Planeta",
        player: "Viajante",
        publish: "Lançar",
      },
    },
  },
  wilds: {
    label: "CHUZI WILDS",
    short_label: "Wilds",
    lexicon: {
      genre: "Biome",
      story: "Grove",
      scene: "Clearing",
      scene_choice: "Trail",
      node: "Seed",
      node_type_choice: "Trail",
      node_type_media: "Bloom",
      node_type_go_to_scene: "Crossing",
      player: "Wanderer",
      library: "Canopy",
      library_open: "Open Canopy",
      library_close: "Close Canopy",
      editor: "Heartwood",
      publish: "Plant",
      experience_realm_idea: "Untamed Nature",
      the_end: "Roots",
      media_pool: "Undergrowth",
      scene_graph: "Canopy",
      watch_path: "Your trail",
      untitled_story: "Untitled Grove",
      unknown_genre: "Unknown Biome",
      scenes_count: "clearings",
      choices_count: "trails",
      drafts_published: "Drafts + Planted",
      published_ver: "Planted ver.",
      draft: "Draft",
      no_scenes_yet: "No clearings in this canopy yet.",
      no_path_yet: "No trail to show yet.",
      menu_empty_drafts: "No groves yet. Plant one to begin.",
      menu_empty_published: "No planted groves in the canopy.",
      menu_published_heading: "Planted groves",
      menu_create_story: "New grove",
      menu_create_film: "Create film",
      film_title_placeholder: "Grove title",
      select_genre: "Select biome",
      genre_field_aria: "Biome",
      delete_story_verb: "Delete grove",
      title_scene_default: "Trailhead",
      choices_made_stat: "trails taken",
      content_rating: "Field Guide",
      content_rating_field_aria: "Field guide",
      select_content_rating: "Select field guide",
      unrated: "Unmarked",
      viewer_credits: "Sap",
      creator_credits: "Pollen",
      editor_media_upload: "Upload Bloom",
      editor_media_preview: "Bloom Preview",
      editor_alt_media: "Effects",
      editor_choices: "Choices",
      editor_scene_settings: "Clearing Settings",
      editor_title_scene: "Start",
      editor_film_title: "Grove Title",
      editor_film_title_hint: "Click to rename this grove",
      editor_ending_scene: "End",
      editor_play: "Unfurl",
      editor_pause: "Rest",
      editor_prev_frame: "Previous Frame",
      editor_next_frame: "Next Frame",
      editor_seek: "Seek",
      editor_no_media: "No bloom assigned",
      editor_uploading: "Blooming\u2026",
      editor_drop_media: "Drop bloom here",
      editor_scene_type: "Clearing Type",
      editor_save: "Engrave",
      editor_cancel: "Cancel",
      editor_create_scene: "Plant Clearing",
      editor_create_scene_plain: "Create New Scene",
      editor_create_scene_cost: "1 Pollen",
      editor_delete_scene_cta: "Delete Scene",
      editor_delete_scene_confirm: "Click again to confirm",
      editor_scene_locked_delete: "Start and end scenes cannot be deleted.",
      editor_scene_color: "Clearing Tint",
      chuzi_ai_name: "Chuzi AI",
      chuzi_ai_create_with: "Create with Chuzi AI",
      chuzi_ai_create_manual: "Enter title manually",
      chuzi_ai_intro: "Answer story-circle prompts and Chuzi AI will grow your short story.",
      chuzi_ai_step_of: "Step",
      chuzi_ai_back: "Back",
      chuzi_ai_next: "Next",
      chuzi_ai_scenes_label: "scenes",
      chuzi_ai_creating: "Creating\u2026",
      chuzi_ai_generate_failed: "Story generation failed.",
      chuzi_ai_build_failed: "Failed to build story.",
      chuzi_ai_generate: "Generate story",
      chuzi_ai_generating: "Generating\u2026",
      chuzi_ai_token_in: "Tokens in",
      chuzi_ai_token_out: "Tokens out",
      chuzi_ai_credits_cost: "AI credits",
      chuzi_ai_scene_credits: "Scene credits",
      chuzi_ai_total_cost: "Total create credits",
      chuzi_ai_insufficient: "Not enough create credits for this generation.",
      chuzi_ai_apply: "Build story",
      chuzi_ai_applying: "Building scenes\u2026",
      chuzi_ai_step_hero: "Hero",
      chuzi_ai_step_hero_hint: "Who is your protagonist? Name, age, personality, and what makes them relatable.",
      chuzi_ai_step_world: "Ordinary world",
      chuzi_ai_step_world_hint: "Where does the story begin? Describe the setting and daily life before adventure calls.",
      chuzi_ai_step_you: "You",
      chuzi_ai_step_you_hint: "The character in a zone of comfort. What is their normal life like right now?",
      chuzi_ai_step_need: "Need",
      chuzi_ai_step_need_hint: "Something isn\u2019t right. What problem, longing, or imbalance disrupts their comfort?",
      chuzi_ai_step_go: "Go",
      chuzi_ai_step_go_hint: "Crossing the threshold. What event pushes them into the unknown?",
      chuzi_ai_step_search: "Search",
      chuzi_ai_step_search_hint: "Trials, growth, and exploration. What challenges and discoveries shape them?",
      chuzi_ai_step_find: "Find",
      chuzi_ai_step_find_hint: "The thing is found or revealed. What truth, object, or insight do they uncover?",
      chuzi_ai_step_take: "Take",
      chuzi_ai_step_take_hint: "Pay the price. What must they sacrifice or confront to claim their goal?",
      chuzi_ai_step_return: "Return",
      chuzi_ai_step_return_hint: "Back to the known world. How do they bring what they learned home?",
      chuzi_ai_step_change: "Change",
      chuzi_ai_step_change_hint: "Transformation achieved. How is the hero different from who they were at the start?",
      chuzi_ai_step_tone: "Tone & mood",
      chuzi_ai_step_tone_hint: "Genre, mood, and atmosphere (e.g. bittersweet sci-fi, cozy mystery, epic fantasy).",
      chuzi_ai_monomyth_hero: "Hero\u2019s Journey: the protagonist",
      chuzi_ai_monomyth_world: "Monomyth: ordinary world",
      chuzi_ai_monomyth_you: "Story Circle: zone of comfort",
      chuzi_ai_monomyth_need: "Story Circle: something isn\u2019t right",
      chuzi_ai_monomyth_go: "Monomyth: crossing the first threshold",
      chuzi_ai_monomyth_search: "Monomyth: road of trials",
      chuzi_ai_monomyth_find: "Monomyth: the ultimate boon",
      chuzi_ai_monomyth_take: "Monomyth: atonement with the father",
      chuzi_ai_monomyth_return: "Monomyth: crossing the return threshold",
      chuzi_ai_monomyth_change: "Monomyth: freedom to live",
      editor_ai_generate: "Grow Bloom",
      editor_ai_generating: "Seed Sprouting\u2026",
      editor_ai_mood_question: "What feeling should this clearing evoke?",
      editor_ai_style_question: "What growth pattern for this bloom?",
      editor_ai_prompt_question: "Describe this clearing",
      editor_ai_accept: "Root Bloom",
      editor_ai_reject: "Prune Bloom",
      editor_ai_retry: "Regrow",
      editor_ai_feedback_prompt: "How should we reshape the growth?",
      editor_ai_credit_cost: "1 Pollen per bloom",
      spending_modal_title: "Gather More Pollen",
      spending_modal_body: "You need more credits to continue. Choose how many to add.",
      spending_modal_no_payment: "Add a payment method to purchase credits.",
      spending_modal_credits_label: "Credits to add",
      spending_modal_price_label: "Total",
      spending_modal_admin_note: "Admin — credits are granted free of charge.",
      spending_modal_purchase: "Purchase Credits",
      spending_modal_grant: "Grant Credits",
      spending_modal_add_card: "Add Payment Method",
      spending_modal_card_last_four: "Card last four digits",
      spending_modal_card_label: "Card label (optional)",
      spending_modal_processing: "Processing\u2026",
      spending_modal_success: "Credits added.",
      spending_modal_error: "Could not complete purchase. Try again.",
      spending_modal_cancel: "Not now",
      spending_insufficient_credits: "Not enough credits. Purchase more to continue.",
      editor_ai_generating_scene: "Clearing emerging\u2026",
      editor_ai_style_badge: "Growth Style",
      editor_ai_failed: "Growth withered. Try regrowing.",
      editor_media_attached: "This clearing already has a bloom rooted.",
      editor_remove_media: "Uproot Bloom",
      editor_media_question: "What's this scene's media?",
      editor_media_type_text: "Text",
      editor_media_type_imagery: "Imagery",
      editor_media_type_film: "Film",
      editor_media_preview_cta: "Preview",
      editor_media_preview_disabled: "Add text to enable preview.",
      editor_text_toolbar_label: "Generator",
      editor_text_font_label: "Font",
      editor_text_color_label: "Text Color",
      editor_text_background_label: "Background",
      editor_text_placeholder: "Start writing scene media...",
      editor_line_add: "Add Text",
      editor_text_lines_section: "Transmission Lines",
      editor_line_editor_label: "Editor",
      editor_line_number: "Line",
      editor_select_line_hint: "Select a transmission line to edit",
      editor_select_effect_hint: "Select an effect to edit",
      editor_select_choice_hint: "Select a choice to edit",
      editor_line_timestamp: "Appears at",
      editor_line_fade_in: "Fade In",
      editor_line_fade_out: "Fade Out",
      editor_line_duration: "Duration",
      editor_line_persist: "Stay on Screen",
      editor_effects_section: "Effects",
      editor_effects_add: "Add sounds, effects, etc",
      editor_effect_fade_in_sound: "Fade In Sound",
      editor_effect_fade_out_sound: "Fade Out Sound",
      editor_effect_fade_in_visual: "Fade In",
      editor_effect_fade_out_visual: "Fade Out",
      editor_timeline_label: "Timeline",
      editor_preview_label: "Preview",
      editor_preview_play: "Play",
      editor_preview_pause: "Pause",
      editor_media_placeholder_imagery: "Imagery authoring is coming soon.",
      editor_media_placeholder_film: "Film authoring is coming soon.",
      editor_goto_scene: "Goto Clearing",
      editor_scene_duration: "Bloom Duration",
      editor_add_choice: "Add Trail",
      editor_arrow_tool: "Place Indicator",
      editor_goto_nullified: "Disabled — trails override goto",
      editor_remove_choice: "Remove Trail",
      editor_choice_target: "Destination Clearing",
      editor_choices_empty_hint: "Set a goto clearing or add a trail to branch the story.",
      editor_goto_none: "None",
      editor_choice_label: "Trail",
      editor_flow_timeline: "Story Flow",
      editor_flow_goto_path: "Default Goto",
      editor_flow_add_choice_here: "Add Trail Here",
      editor_flow_choice_branch: "Branch",
      editor_flow_content_ref: "Content",
      editor_scene_duration_unit: "seconds",
      editor_scene_duration_override_hint: "Overrides bloom length. Content runtime: {duration}s",
      editor_arrow_scale: "Span",
      editor_arrow_rotation: "Bearing",
      editor_arrow_rotate_hint: "Drag the beacon above the indicator in preview to rotate",
      constellation_no_coverbox: "Unseen",
      hud_edit_control: "Tend",
      hud_delete_control: "Uproot",
      hud_publish_control: "Plant",
      hud_launch_control: "Enter",
      editor_publish_story: "Share",
      viewer_loading: "Entering the grove…",
      viewer_preparing: "Gathering blooms…",
      viewer_close: "Leave",
      viewer_complete: "Journey complete",
      viewer_stage_label: "Canopy",
      viewer_choose_path: "Choose",
      create_button: "CREATE",
      publish_form_heading: "Planting check",
      tags_label: "Root Tags",
      tags_placeholder: "Search root tags\u2026",
      tags_empty: "No root tags yet",
      tags_required: "At least one root tag is required.",
      story_picker_label: "Groves",
      created_by: "Tended by",
      chosen_by: "Chosen by",
      story_metadata_heading: "Grove details",
      story_metadata_save: "Save",
      constellation_title_edit_hint: "Edit grove title and details",
      director_profile_title: "Director profile",
      director_profile_name_label: "Name",
      director_profile_realm_label: "Experience realm",
      director_profile_image_label: "Image",
      director_profile_image_hint:
        "Realm-themed seal — switching the realm above swaps the seal. Custom uploads land with the V1 avatar endpoints.",
      director_profile_tab_profile: "Profile",
      director_profile_tab_experience_mapping: "Experience Mapping",
      director_profile_admin_only: "Admin only",
      director_profile_cancel: "Cancel",
      director_profile_close: "Close",
      director_profile_save: "Save",
      director_profile_saving: "Saving…",
      director_profile_name_required: "Name is required.",
      director_profile_save_failed: "Save failed",
      experience_mapping_loading: "Loading experience mapping…",
      experience_mapping_empty: "No template hierarchy available yet.",
      experience_mapping_retry: "Retry",
      experience_mapping_story_label: "Story",
      experience_mapping_scene_label: "Scene",
      experience_mapping_action_label: "Action",
      experience_mapping_field_title: "Title",
      experience_mapping_field_description: "Description",
      experience_mapping_field_genre: "Genre",
      experience_mapping_field_content_rating: "Content rating",
      experience_mapping_field_color: "Color",
      experience_mapping_field_name: "Name",
      experience_mapping_field_type: "Type",
      experience_mapping_field_order: "Order",
      experience_mapping_field_duration: "Duration",
      experience_mapping_field_properties: "Properties",
      experience_mapping_field_subproperties: "Subproperties",
      experience_mapping_save_changes: "Save changes",
      experience_mapping_saved: "Saved",
      experience_mapping_save_error: "Could not save changes.",
      experience_mapping_delete_story: "Delete story",
      experience_mapping_delete_scene: "Delete scene",
      experience_mapping_delete_action: "Delete action",
      experience_mapping_delete_confirm: "Click again to confirm",
      experience_mapping_delete_error: "Delete failed.",
      experience_mapping_expand_all: "Expand all",
      experience_mapping_collapse_all: "Collapse all",
      experience_mapping_forbidden: "You do not have admin access for this section.",
      experience_mapping_bad_json: "JSON must be valid before saving.",
      experience_mapping_intro:
        "Edit realm vocabulary from largest to smallest. Generate JSON and paste it in chat for code application.",
      experience_mapping_dirty: "dirty changes",
      experience_mapping_export_ready: "No unsaved mapping edits yet.",
      experience_mapping_export_json: "Generate JSON export",
      experience_mapping_copy_json: "Copy JSON",
      experience_mapping_copied: "Copied",
      experience_mapping_paste_instruction:
        "Paste this JSON in chat and I will apply it to chuzi-shared.",
      experience_mapping_export_empty: "Export output appears here.",
      experience_mapping_select_realm: "Select realm",
      experience_mapping_group_major_idea: "Major Idea",
      experience_mapping_helper_realm_idea:
        "Highest-level concept for this realm.",
      experience_mapping_save_experience: "Save to experience",
      experience_mapping_saved_experience:
        "Saved to current experience. Some labels appear immediately.",
      auth_email_placeholder: "Email",
      auth_password_input_placeholder: "Password",
      auth_password_sign_in_button: "Sign In",
      auth_password_signing_in: "Signing in...",
      auth_signin_tab: "Sign in",
      auth_signup_tab: "Sign up",
      auth_signup_subtitle: "Create your account with secure sign-in.",
      auth_signin_subtitle: "Sign in with your account provider.",
      auth_sign_up_button: "Continue with Google",
      auth_username_placeholder: "Username",
      auth_sign_in_button: "Continue with Google",
      auth_signing_in: "Signing in...",
      auth_oidc_redirecting: "Redirecting to secure sign-in...",
      auth_oidc_failed: "Could not start sign-in.",
      auth_oidc_callback_processing: "Completing sign-in...",
      auth_oidc_verified: "Signed in. Redirecting...",
      auth_oidc_callback_failed: "Could not complete sign-in.",
      auth_oidc_token_missing: "Sign-in token was missing.",
      auth_magic_link_sent:
        "If that email is registered, a magic link has been sent.",
      auth_magic_link_sent_signup: "Check your email for your sign-up link.",
      auth_magic_link_verifying: "Verifying magic link...",
      auth_magic_link_verified: "Signed in. Redirecting...",
      auth_magic_link_failed: "This magic link is invalid or expired.",
      auth_magic_link_cta: "Use another email",
      auth_login_failed: "Sign-in failed.",
      auth_username_checking: "Checking username availability...",
      auth_username_available: "Username is available.",
      auth_username_unavailable: "Username is taken; updated to an available suggestion.",
      auth_username_required: "Username is required.",
      auth_username_update_failed: "Could not reserve a unique username.",
      experience_mapping_group_experience_root: "Experience Root",
      experience_mapping_group_node_types: "Node Types",
      experience_mapping_group_scene_structure: "Scene Structure",
      experience_mapping_group_media: "Media Terms",
      experience_mapping_group_counts: "Counts and Adjacent Labels",
      experience_mapping_helper_story: "Largest narrative unit.",
      experience_mapping_helper_scene: "Contained unit under story.",
      experience_mapping_helper_scene_choice: "Branching choice in a scene.",
      experience_mapping_helper_node: "Smallest flow node.",
      experience_mapping_helper_alt_media: "Smallest related media label.",
    },
    locales: {
      es: {
        genre: "Bioma",
        story: "Arboleda",
        scene: "Claro",
        scene_choice: "Sendero",
        player: "Errante",
        library: "Dosel",
        editor: "Duramen",
        publish: "Plantar",
        the_end: "Raíces",
        untitled_story: "Arboleda sin título",
        menu_create_story: "Nueva arboleda",
        film_title_placeholder: "Título de la arboleda",
        select_genre: "Seleccionar bioma",
        created_by: "Cuidado por",
      },
      fr: {
        genre: "Biome",
        story: "Bosquet",
        scene: "Clairière",
        scene_choice: "Sentier",
        player: "Vagabond",
        library: "Canopée",
        editor: "Cœur de bois",
        publish: "Planter",
        the_end: "Racines",
        untitled_story: "Bosquet sans titre",
        menu_create_story: "Nouveau bosquet",
        film_title_placeholder: "Titre du bosquet",
        select_genre: "Sélectionner un biome",
        created_by: "Soigné par",
      },
      de: {
        genre: "Biom",
        story: "Hain",
        scene: "Lichtung",
        player: "Wanderer",
        publish: "Pflanzen",
      },
      pt: {
        genre: "Bioma",
        story: "Bosque",
        scene: "Clareira",
        player: "Andarilho",
        publish: "Plantar",
      },
    },
  },
};

export const FALLBACK_LEXICON: Record<string, string> = {
  genre: "Genre",
  story: "Story",
  scene: "Scene",
  scene_choice: "Choice",
  node: "Node",
  node_type_choice: "Choice",
  node_type_media: "Media",
  node_type_go_to_scene: "Go to scene",
  player: "Player",
  library: "Library",
  library_open: "Open scene tree",
  library_close: "Close scene tree",
  editor: "Editor",
  publish: "Publish",
  experience_realm_idea: "Experience Theme",
  the_end: "The End",
  media_pool: "Media Pool",
  scene_graph: "Scene tree",
  watch_path: "Your path",
  untitled_story: "Untitled Story",
  unknown_genre: "Unknown Genre",
  scenes_count: "scenes",
  choices_count: "choices",
  drafts_published: "Drafts + Published",
  published_ver: "Published ver.",
  draft: "Draft",
  no_scenes_yet: "No scenes available yet.",
  no_path_yet: "No path to show yet.",
  menu_empty_drafts: "No films yet. Create one to get started.",
  menu_empty_published: "No published films found.",
  menu_published_heading: "Published Films",
  menu_create_story: "Create Story",
  menu_create_film: "Create Film",
  film_title_placeholder: "Film title",
  select_genre: "Select genre",
  genre_field_aria: "Film genre",
  delete_story_verb: "Delete film",
  title_scene_default: "Start",
  choices_made_stat: "choices made",
  content_rating: "Rating",
  content_rating_field_aria: "Content rating",
  select_content_rating: "Select rating",
  unrated: "Not Rated",
  viewer_credits: "Viewer Credits",
  creator_credits: "Creator Credits",
  editor_media_upload: "Upload Media",
  editor_media_preview: "Media Preview",
  editor_alt_media: "Effects",
  editor_choices: "Choices",
  editor_scene_settings: "Scene Settings",
  editor_title_scene: "Start",
  editor_film_title: "Film Title",
  editor_film_title_hint: "Click to rename this film",
  editor_ending_scene: "End",
  editor_play: "Play",
  editor_pause: "Pause",
  editor_prev_frame: "Previous Frame",
  editor_next_frame: "Next Frame",
  editor_seek: "Seek",
  editor_no_media: "No media assigned",
  editor_uploading: "Uploading\u2026",
  editor_drop_media: "Drop media here",
  editor_scene_type: "Scene Type",
  editor_save: "Save",
  editor_cancel: "Cancel",
  editor_create_scene: "Create Scene",
  editor_create_scene_plain: "Create New Scene",
  editor_create_scene_cost: "1 credit",
  editor_delete_scene_cta: "Delete Scene",
  editor_delete_scene_confirm: "Click again to confirm",
  editor_scene_locked_delete: "Start and end scenes cannot be deleted.",
  editor_scene_color: "Scene Color",
  chuzi_ai_name: "Chuzi AI",
  chuzi_ai_create_with: "Create with Chuzi AI",
  chuzi_ai_create_manual: "Enter title manually",
  chuzi_ai_intro: "Answer a few story-circle prompts and Chuzi AI will draft your short story.",
  chuzi_ai_step_of: "Step",
  chuzi_ai_back: "Back",
  chuzi_ai_next: "Next",
  chuzi_ai_scenes_label: "scenes",
  chuzi_ai_creating: "Creating\u2026",
  chuzi_ai_generate_failed: "Story generation failed.",
  chuzi_ai_build_failed: "Failed to build story.",
  chuzi_ai_generate: "Generate story",
  chuzi_ai_generating: "Generating\u2026",
  chuzi_ai_token_in: "Tokens in",
  chuzi_ai_token_out: "Tokens out",
  chuzi_ai_credits_cost: "AI credits",
  chuzi_ai_scene_credits: "Scene credits",
  chuzi_ai_total_cost: "Total create credits",
  chuzi_ai_insufficient: "Not enough create credits for this generation.",
  chuzi_ai_apply: "Build story",
  chuzi_ai_applying: "Building scenes\u2026",
  chuzi_ai_step_hero: "Hero",
  chuzi_ai_step_hero_hint: "Who is your protagonist? Name, age, personality, and what makes them relatable.",
  chuzi_ai_step_world: "Ordinary world",
  chuzi_ai_step_world_hint: "Where does the story begin? Describe the setting and daily life before adventure calls.",
  chuzi_ai_step_you: "You",
  chuzi_ai_step_you_hint: "The character in a zone of comfort. What is their normal life like right now?",
  chuzi_ai_step_need: "Need",
  chuzi_ai_step_need_hint: "Something isn\u2019t right. What problem, longing, or imbalance disrupts their comfort?",
  chuzi_ai_step_go: "Go",
  chuzi_ai_step_go_hint: "Crossing the threshold. What event pushes them into the unknown?",
  chuzi_ai_step_search: "Search",
  chuzi_ai_step_search_hint: "Trials, growth, and exploration. What challenges and discoveries shape them?",
  chuzi_ai_step_find: "Find",
  chuzi_ai_step_find_hint: "The thing is found or revealed. What truth, object, or insight do they uncover?",
  chuzi_ai_step_take: "Take",
  chuzi_ai_step_take_hint: "Pay the price. What must they sacrifice or confront to claim their goal?",
  chuzi_ai_step_return: "Return",
  chuzi_ai_step_return_hint: "Back to the known world. How do they bring what they learned home?",
  chuzi_ai_step_change: "Change",
  chuzi_ai_step_change_hint: "Transformation achieved. How is the hero different from who they were at the start?",
  chuzi_ai_step_tone: "Tone & mood",
  chuzi_ai_step_tone_hint: "Genre, mood, and atmosphere (e.g. bittersweet sci-fi, cozy mystery, epic fantasy).",
  chuzi_ai_monomyth_hero: "Hero\u2019s Journey: the protagonist",
  chuzi_ai_monomyth_world: "Monomyth: ordinary world",
  chuzi_ai_monomyth_you: "Story Circle: zone of comfort",
  chuzi_ai_monomyth_need: "Story Circle: something isn\u2019t right",
  chuzi_ai_monomyth_go: "Monomyth: crossing the first threshold",
  chuzi_ai_monomyth_search: "Monomyth: road of trials",
  chuzi_ai_monomyth_find: "Monomyth: the ultimate boon",
  chuzi_ai_monomyth_take: "Monomyth: atonement with the father",
  chuzi_ai_monomyth_return: "Monomyth: crossing the return threshold",
  chuzi_ai_monomyth_change: "Monomyth: freedom to live",
  editor_ai_generate: "Generate with AI",
  editor_ai_generating: "Generating\u2026",
  editor_ai_mood_question: "What mood should this scene convey?",
  editor_ai_style_question: "What visual style do you want?",
  editor_ai_prompt_question: "Describe this scene",
  editor_ai_accept: "Accept",
  editor_ai_reject: "Reject",
  editor_ai_retry: "Try Again",
  editor_ai_feedback_prompt: "What should we change?",
  editor_ai_credit_cost: "1 credit per generation",
  spending_modal_title: "Purchase Credits",
  spending_modal_body: "You need more credits to continue. Choose how many to add.",
  spending_modal_no_payment: "Add a payment method to purchase credits.",
  spending_modal_credits_label: "Credits to add",
  spending_modal_price_label: "Total",
  spending_modal_admin_note: "Admin — credits are granted free of charge.",
  spending_modal_purchase: "Purchase Credits",
  spending_modal_grant: "Grant Credits",
  spending_modal_add_card: "Add Payment Method",
  spending_modal_card_last_four: "Card last four digits",
  spending_modal_card_label: "Card label (optional)",
  spending_modal_processing: "Processing\u2026",
  spending_modal_success: "Credits added.",
  spending_modal_error: "Could not complete purchase. Try again.",
  spending_modal_cancel: "Not now",
  spending_insufficient_credits: "Not enough credits. Purchase more to continue.",
  editor_ai_generating_scene: "Scene generating\u2026",
  editor_ai_style_badge: "Style",
  editor_ai_failed: "Generation failed. Please try again.",
  editor_media_attached: "This scene already has media attached.",
  editor_remove_media: "Remove Media",
  editor_media_question: "What's this scene's media?",
  editor_media_type_text: "Text",
  editor_media_type_imagery: "Imagery",
  editor_media_type_film: "Film",
  editor_media_preview_cta: "Preview",
  editor_media_preview_disabled: "Add text to enable preview.",
  editor_text_toolbar_label: "Generator",
  editor_text_font_label: "Font",
  editor_text_color_label: "Text Color",
  editor_text_background_label: "Background",
  editor_text_placeholder: "Start writing scene media...",
  editor_line_add: "Add Text",
  editor_text_lines_section: "Text Lines",
  editor_line_editor_label: "Editor",
  editor_line_number: "Line",
  editor_select_line_hint: "Select a line to edit",
  editor_select_effect_hint: "Select an effect to edit",
  editor_select_choice_hint: "Select a choice to edit",
  editor_line_timestamp: "Appears at",
  editor_line_fade_in: "Fade In",
  editor_line_fade_out: "Fade Out",
  editor_line_duration: "Duration",
  editor_line_persist: "Stay on Screen",
  editor_effects_section: "Effects",
  editor_effects_add: "Add sounds, effects, etc",
  editor_effect_fade_in_sound: "Fade In Sound",
  editor_effect_fade_out_sound: "Fade Out Sound",
  editor_effect_fade_in_visual: "Fade In",
  editor_effect_fade_out_visual: "Fade Out",
  editor_timeline_label: "Timeline",
  editor_preview_label: "Preview",
  editor_preview_play: "Play",
  editor_preview_pause: "Pause",
  editor_media_placeholder_imagery: "Imagery authoring is coming soon.",
  editor_media_placeholder_film: "Film authoring is coming soon.",
  editor_goto_scene: "Goto Scene",
  editor_scene_duration: "Scene Duration",
  editor_add_choice: "Add Choice",
  editor_arrow_tool: "Place Arrow",
  editor_goto_nullified: "Disabled — choices override goto",
  editor_remove_choice: "Remove Choice",
  editor_choice_target: "Destination Scene",
  editor_choices_empty_hint: "Set a goto scene or add a choice to create branching paths.",
  editor_goto_none: "None",
  editor_choice_label: "Choice",
  editor_flow_timeline: "Story Flow",
  editor_flow_goto_path: "Default Goto",
  editor_flow_add_choice_here: "Add Choice Here",
  editor_flow_choice_branch: "Branch",
  editor_flow_content_ref: "Content",
  editor_scene_duration_unit: "seconds",
  editor_scene_duration_override_hint: "Overrides preview playback length. Content: {duration}s",
  editor_arrow_scale: "Scale",
  editor_arrow_rotation: "Rotation",
  editor_arrow_rotate_hint: "Drag the handle above the arrow in preview to rotate",
  constellation_no_coverbox: "No cover",
  hud_edit_control: "Edit",
  hud_delete_control: "Delete",
  hud_publish_control: "Publish",
  hud_launch_control: "Launch",
  editor_publish_story: "Publish",
  viewer_loading: "Loading experience…",
  viewer_preparing: "Cueing media…",
  viewer_close: "Exit",
  viewer_complete: "Experience complete",
  viewer_stage_label: "Experience",
  viewer_choose_path: "Choose",
  create_button: "CREATE",
  publish_form_heading: "Publish checklist",
  tags_label: "Tags",
  tags_placeholder: "Search tags\u2026",
  tags_empty: "No tags yet",
  tags_required: "At least one tag is required.",
  story_picker_label: "Stories",
  created_by: "Created by",
  chosen_by: "Chosen by",
  story_metadata_heading: "Story details",
  story_metadata_save: "Save",
  constellation_title_edit_hint: "Edit story title and details",
  director_profile_title: "Director profile",
  director_profile_name_label: "Name",
  director_profile_realm_label: "Experience realm",
  director_profile_image_label: "Image",
  director_profile_image_hint:
    "Realm-themed seal — switching the realm above swaps the seal. Custom uploads land with the V1 avatar endpoints.",
  director_profile_tab_profile: "Profile",
  director_profile_tab_experience_mapping: "Experience Mapping",
  director_profile_admin_only: "Admin only",
  director_profile_cancel: "Cancel",
  director_profile_close: "Close",
  director_profile_save: "Save",
  director_profile_saving: "Saving…",
  director_profile_name_required: "Name is required.",
  director_profile_save_failed: "Save failed",
  experience_mapping_loading: "Loading experience mapping…",
  experience_mapping_empty: "No template hierarchy available yet.",
  experience_mapping_retry: "Retry",
  experience_mapping_story_label: "Story",
  experience_mapping_scene_label: "Scene",
  experience_mapping_action_label: "Action",
  experience_mapping_field_title: "Title",
  experience_mapping_field_description: "Description",
  experience_mapping_field_genre: "Genre",
  experience_mapping_field_content_rating: "Content rating",
  experience_mapping_field_color: "Color",
  experience_mapping_field_name: "Name",
  experience_mapping_field_type: "Type",
  experience_mapping_field_order: "Order",
  experience_mapping_field_duration: "Duration",
  experience_mapping_field_properties: "Properties",
  experience_mapping_field_subproperties: "Subproperties",
  experience_mapping_save_changes: "Save changes",
  experience_mapping_saved: "Saved",
  experience_mapping_save_error: "Could not save changes.",
  experience_mapping_delete_story: "Delete story",
  experience_mapping_delete_scene: "Delete scene",
  experience_mapping_delete_action: "Delete action",
  experience_mapping_delete_confirm: "Click again to confirm",
  experience_mapping_delete_error: "Delete failed.",
  experience_mapping_expand_all: "Expand all",
  experience_mapping_collapse_all: "Collapse all",
  experience_mapping_forbidden: "You do not have admin access for this section.",
  experience_mapping_bad_json: "JSON must be valid before saving.",
  experience_mapping_intro:
    "Edit realm vocabulary from largest to smallest. Generate JSON and paste it in chat for code application.",
  experience_mapping_dirty: "dirty changes",
  experience_mapping_export_ready: "No unsaved mapping edits yet.",
  experience_mapping_export_json: "Generate JSON export",
  experience_mapping_copy_json: "Copy JSON",
  experience_mapping_copied: "Copied",
  experience_mapping_paste_instruction:
    "Paste this JSON in chat and I will apply it to chuzi-shared.",
  experience_mapping_export_empty: "Export output appears here.",
  experience_mapping_select_realm: "Select realm",
  experience_mapping_group_major_idea: "Major Idea",
  experience_mapping_helper_realm_idea:
    "Highest-level concept for this realm.",
  experience_mapping_save_experience: "Save to experience",
  experience_mapping_saved_experience:
    "Saved to current experience. Some labels appear immediately.",
  auth_email_placeholder: "Email",
  auth_password_input_placeholder: "Password",
  auth_password_sign_in_button: "Sign In",
  auth_password_signing_in: "Signing in...",
  auth_signin_tab: "Sign in",
  auth_signup_tab: "Sign up",
  auth_signup_subtitle: "Create your account with secure sign-in.",
  auth_signin_subtitle: "Sign in with your account provider.",
  auth_sign_up_button: "Continue with Google",
  auth_username_placeholder: "Username",
  auth_sign_in_button: "Continue with Google",
  auth_signing_in: "Signing in...",
  auth_oidc_redirecting: "Redirecting to secure sign-in...",
  auth_oidc_failed: "Could not start sign-in.",
  auth_oidc_callback_processing: "Completing sign-in...",
  auth_oidc_verified: "Signed in. Redirecting...",
  auth_oidc_callback_failed: "Could not complete sign-in.",
  auth_oidc_token_missing: "Sign-in token was missing.",
  auth_magic_link_sent:
    "If that email is registered, a magic link has been sent.",
  auth_magic_link_sent_signup: "Check your email for your sign-up link.",
  auth_magic_link_verifying: "Verifying magic link...",
  auth_magic_link_verified: "Signed in. Redirecting...",
  auth_magic_link_failed: "This magic link is invalid or expired.",
  auth_magic_link_cta: "Use another email",
  auth_login_failed: "Sign-in failed.",
  auth_username_checking: "Checking username availability...",
  auth_username_available: "Username is available.",
  auth_username_unavailable: "Username is taken; updated to an available suggestion.",
  auth_username_required: "Username is required.",
  auth_username_update_failed: "Could not reserve a unique username.",
  experience_mapping_group_experience_root: "Experience Root",
  experience_mapping_group_node_types: "Node Types",
  experience_mapping_group_scene_structure: "Scene Structure",
  experience_mapping_group_media: "Media Terms",
  experience_mapping_group_counts: "Counts and Adjacent Labels",
  experience_mapping_helper_story: "Largest narrative unit.",
  experience_mapping_helper_scene: "Contained unit under story.",
  experience_mapping_helper_scene_choice: "Branching choice in a scene.",
  experience_mapping_helper_node: "Smallest flow node.",
  experience_mapping_helper_alt_media: "Smallest related media label.",
};

/**
 * Per-locale overrides for FALLBACK_LEXICON. Missing keys fall through to
 * the English fallback. Mirrors PHP `chuzi_realms.fallback_locales`.
 */
export const FALLBACK_LOCALES: Partial<
  Record<LocaleId, Record<string, string>>
> = {
  es: {
    genre: "Género",
    story: "Historia",
    scene: "Escena",
    scene_choice: "Elección",
    player: "Reproductor",
    library: "Biblioteca",
    editor: "Editor",
    publish: "Publicar",
    the_end: "Fin",
    untitled_story: "Historia sin título",
    menu_create_story: "Crear historia",
    menu_create_film: "Crear película",
    film_title_placeholder: "Título de la película",
    select_genre: "Seleccionar género",
    delete_story_verb: "Eliminar película",
    created_by: "Creado por",
  },
  fr: {
    genre: "Genre",
    story: "Histoire",
    scene: "Scène",
    scene_choice: "Choix",
    player: "Lecteur",
    library: "Bibliothèque",
    editor: "Éditeur",
    publish: "Publier",
    the_end: "Fin",
    untitled_story: "Histoire sans titre",
    menu_create_story: "Créer une histoire",
    menu_create_film: "Créer un film",
    film_title_placeholder: "Titre du film",
    select_genre: "Sélectionner un genre",
    delete_story_verb: "Supprimer le film",
    created_by: "Créé par",
  },
  de: {
    genre: "Genre",
    story: "Geschichte",
    scene: "Szene",
    publish: "Veröffentlichen",
    the_end: "Ende",
    untitled_story: "Unbenannte Geschichte",
    menu_create_story: "Geschichte erstellen",
    film_title_placeholder: "Filmtitel",
    select_genre: "Genre auswählen",
    created_by: "Erstellt von",
  },
  pt: {
    genre: "Gênero",
    story: "História",
    scene: "Cena",
    publish: "Publicar",
    the_end: "Fim",
    untitled_story: "História sem título",
    menu_create_story: "Criar história",
    film_title_placeholder: "Título do filme",
    select_genre: "Selecionar gênero",
    created_by: "Criado por",
  },
};

function resolveFallback(locale: LocaleId | null | undefined): Record<string, string> {
  const overrides = locale && FALLBACK_LOCALES[locale];
  return overrides ? { ...FALLBACK_LEXICON, ...overrides } : { ...FALLBACK_LEXICON };
}

function resolveRealm(
  realmId: RealmId,
  locale: LocaleId | null | undefined
): Record<string, string> {
  const realm = REALMS[realmId];
  const overrides = locale && realm.locales ? realm.locales[locale] : undefined;
  const runtimeOverrides = runtimeRealmLexiconOverrides[realmId];
  return {
    ...realm.lexicon,
    ...(overrides ?? {}),
    ...(runtimeOverrides ?? {}),
  };
}

/**
 * Get a lexicon value for a realm + locale, falling back to the neutral
 * lexicon (which itself respects locale).
 */
export function t(
  realmId: RealmId | null | undefined,
  key: string,
  fallback = "",
  locale: LocaleId | null | undefined = null
): string {
  if (realmId && REALMS[realmId]) {
    const realmLex = resolveRealm(realmId, locale);
    if (realmLex[key] !== undefined) return realmLex[key];
  }
  const fb = resolveFallback(locale);
  return fb[key] ?? fallback;
}

/**
 * Get the full merged lexicon for a realm + locale (realm lexicon on top of
 * locale-aware fallback).
 */
export function lexiconForRealm(
  realmId: RealmId | null | undefined,
  locale: LocaleId | null | undefined = null
): Record<string, string> {
  const fb = resolveFallback(locale);
  if (!realmId || !REALMS[realmId]) {
    return fb;
  }
  return { ...fb, ...resolveRealm(realmId, locale) };
}
