import type {
  RealmId,
  RealmDefinition,
  ContentRating,
  ContentRatingDefinition,
  LocaleId,
} from "../types/index.js";

export const REALM_IDS: readonly RealmId[] = ["cosmos", "wilds"] as const;

export const SUPPORTED_LOCALES: readonly LocaleId[] = [
  "en",
  "es",
  "fr",
  "de",
  "pt",
] as const;

export const LOCALE_LABELS: Record<LocaleId, string> = {
  en: "English",
  es: "Español",
  fr: "Français",
  de: "Deutsch",
  pt: "Português",
};

export const DEFAULT_LOCALE: LocaleId = "en";

type RealmLexiconOverrides = Partial<Record<RealmId, Record<string, string>>>;
let runtimeRealmLexiconOverrides: RealmLexiconOverrides = {};

export function getRealmLexiconOverrides(): RealmLexiconOverrides {
  return {
    cosmos: runtimeRealmLexiconOverrides.cosmos
      ? { ...runtimeRealmLexiconOverrides.cosmos }
      : undefined,
    wilds: runtimeRealmLexiconOverrides.wilds
      ? { ...runtimeRealmLexiconOverrides.wilds }
      : undefined,
  };
}

export function setRealmLexiconOverrides(overrides: RealmLexiconOverrides): void {
  runtimeRealmLexiconOverrides = {
    cosmos: overrides.cosmos ? { ...overrides.cosmos } : undefined,
    wilds: overrides.wilds ? { ...overrides.wilds } : undefined,
  };
}

export function isSupportedLocale(value: unknown): value is LocaleId {
  return (
    typeof value === "string" &&
    SUPPORTED_LOCALES.includes(value as LocaleId)
  );
}

/**
 * Normalize a raw locale tag (e.g. "en-US", "pt_BR") to a supported LocaleId,
 * matching the PHP `LocaleResolver::normalize` behavior.
 */
export function normalizeLocale(value: string | null | undefined): LocaleId | null {
  if (!value) return null;
  const lower = value.toLowerCase().trim();
  if (isSupportedLocale(lower)) return lower;
  const base = lower.split(/[-_]/, 1)[0];
  return isSupportedLocale(base) ? base : null;
}

/**
 * Pick the best supported locale from a browser Accept-Language string.
 * Mirrors PHP `LocaleResolver::matchAcceptLanguage` (q-value aware).
 */
export function matchAcceptLanguage(
  accept: string | null | undefined
): LocaleId | null {
  if (!accept) return null;
  const tags = accept
    .split(",")
    .map((part) => {
      const [tag, ...params] = part.trim().split(";");
      const qParam = params.find((p) => p.trim().startsWith("q="));
      const q = qParam ? parseFloat(qParam.split("=")[1]) || 0 : 1;
      return { tag: tag.trim(), q };
    })
    .filter((c) => c.tag && c.tag !== "*")
    .sort((a, b) => b.q - a.q);

  for (const c of tags) {
    const normalized = normalizeLocale(c.tag);
    if (normalized) return normalized;
  }
  return null;
}

export const CONTENT_RATING_IDS: readonly ContentRating[] = [
  "G",
  "PG",
  "PG-13",
  "R",
  "NC-17",
] as const;

export const CONTENT_RATINGS: Record<ContentRating, ContentRatingDefinition> = {
  G: {
    id: "G",
    label: "G",
    description: "General Audiences — all ages admitted.",
  },
  PG: {
    id: "PG",
    label: "PG",
    description: "Parental Guidance Suggested — some material may not be suitable for children.",
  },
  "PG-13": {
    id: "PG-13",
    label: "PG-13",
    description: "Parents Strongly Cautioned — some material may be inappropriate for children under 13.",
  },
  R: {
    id: "R",
    label: "R",
    description: "Restricted — under 17 requires accompanying parent or adult guardian.",
  },
  "NC-17": {
    id: "NC-17",
    label: "NC-17",
    description: "Adults Only — no one 17 and under admitted.",
  },
};

export function isContentRating(value: unknown): value is ContentRating {
  return typeof value === "string" && CONTENT_RATING_IDS.includes(value as ContentRating);
}

export const REALMS: Record<RealmId, RealmDefinition> = {
  cosmos: {
    label: "CHUZI COSMOS",
    short_label: "Cosmos",
    lexicon: {
      genre: "Galaxy",
      story: "Star System",
      scene: "Planet",
      scene_choice: "Trajectory",
      node: "Signal",
      node_type_choice: "Trajectory",
      node_type_media: "Transmission",
      node_type_go_to_scene: "Warp",
      player: "Voyager",
      library: "Star Chart",
      library_open: "Open Star Chart",
      library_close: "Close Star Chart",
      editor: "Mission Control",
      publish: "Launch",
      experience_realm_idea: "Outer Space",
      the_end: "The End",
      media_pool: "Cargo Bay",
      scene_graph: "Star Chart",
      watch_path: "Your trajectory",
      untitled_story: "Untitled Star System",
      unknown_genre: "Unknown Galaxy",
      scenes_count: "planets",
      choices_count: "trajectories",
      drafts_published: "Drafts + Launched",
      published_ver: "Launched ver.",
      draft: "Draft",
      no_scenes_yet: "No planets in this chart yet.",
      no_path_yet: "No trajectory to show yet.",
      menu_empty_drafts: "No star systems yet. Chart one to begin.",
      menu_empty_published: "No launched systems in the chart.",
      menu_published_heading: "Launched constellations",
      menu_create_story: "New star system",
      menu_create_film: "Create film",
      film_title_placeholder: "Star system title",
      select_genre: "Select galaxy",
      genre_field_aria: "Galaxy",
      delete_story_verb: "Delete star system",
      title_scene_default: "Title planet",
      choices_made_stat: "trajectories taken",
      content_rating: "Audience Class",
      content_rating_field_aria: "Audience class",
      select_content_rating: "Select audience class",
      unrated: "Unclassified",
      viewer_credits: "Fuel Cells",
      creator_credits: "Stardust",
      editor_media_upload: "Upload Transmission",
      editor_media_preview: "Transmission Preview",
      editor_alt_media: "Additional Media",
      editor_choices: "Choices",
      editor_scene_settings: "Star Settings",
      editor_title_scene: "Title Star",
      editor_ending_scene: "Final Star",
      editor_play: "Engage",
      editor_pause: "Hold",
      editor_prev_frame: "Previous Frame",
      editor_next_frame: "Next Frame",
      editor_seek: "Seek",
      editor_no_media: "No transmission assigned",
      editor_uploading: "Transmitting\u2026",
      editor_drop_media: "Drop transmission here",
      editor_scene_type: "Star Type",
      editor_save: "Lock In",
      editor_cancel: "Abort",
      editor_create_scene: "Chart Planet",
      editor_create_scene_plain: "Create New Scene",
      editor_create_scene_cost: "1 Stardust",
      editor_delete_scene_cta: "Delete Scene",
      editor_delete_scene_confirm: "Click again to confirm",
      editor_scene_locked_delete: "Title and end scenes cannot be deleted.",
      editor_scene_color: "Star Hue",
      editor_ai_generate: "Generate Transmission",
      editor_ai_generating: "Transmitting Signal\u2026",
      editor_ai_mood_question: "What energy should this planet radiate?",
      editor_ai_style_question: "What vision style for this transmission?",
      editor_ai_prompt_question: "Describe this planet\u2019s landscape",
      editor_ai_accept: "Lock Transmission",
      editor_ai_reject: "Reject Signal",
      editor_ai_retry: "Retransmit",
      editor_ai_feedback_prompt: "How should we adjust the signal?",
      editor_ai_credit_cost: "1 Stardust per signal",
      editor_ai_generating_scene: "Planet forming\u2026",
      editor_ai_style_badge: "Signal Style",
      editor_ai_failed: "Signal lost. Try retransmitting.",
      editor_media_attached: "This star already has a transmission locked in.",
      editor_remove_media: "Remove Transmission",
      editor_media_question: "What's this scene's media?",
      editor_media_type_text: "Text",
      editor_media_type_imagery: "Imagery",
      editor_media_type_film: "Film",
      editor_media_preview_cta: "Preview",
      editor_media_preview_disabled: "Add text to enable preview.",
      editor_text_toolbar_label: "Generator",
      editor_text_font_label: "Font",
      editor_text_color_label: "Text Color",
      editor_text_background_label: "Background",
      editor_text_placeholder: "Start writing scene media...",
      editor_media_placeholder_imagery: "Imagery authoring is coming soon.",
      editor_media_placeholder_film: "Film authoring is coming soon.",
      constellation_no_coverbox: "Uncharted",
      hud_edit_control: "Engage",
      hud_delete_control: "Jettison",
      hud_publish_control: "Launch",
      create_button: "CREATE",
      publish_form_heading: "Launch readiness",
      tags_label: "Signal Tags",
      tags_placeholder: "Search signal tags\u2026",
      tags_empty: "No signal tags yet",
      story_picker_label: "Constellations",
      created_by: "Directed by",
      director_profile_title: "Director profile",
      director_profile_name_label: "Name",
      director_profile_realm_label: "Experience realm",
      director_profile_image_label: "Image",
      director_profile_image_hint:
        "Realm-themed seal — switching the realm above swaps the seal. Custom uploads land with the V1 avatar endpoints.",
      director_profile_tab_profile: "Profile",
      director_profile_tab_experience_mapping: "Experience Mapping",
      director_profile_admin_only: "Admin only",
      director_profile_cancel: "Cancel",
      director_profile_save: "Save",
      director_profile_saving: "Saving…",
      director_profile_name_required: "Name is required.",
      director_profile_save_failed: "Save failed",
      experience_mapping_loading: "Loading experience mapping…",
      experience_mapping_empty: "No template hierarchy available yet.",
      experience_mapping_retry: "Retry",
      experience_mapping_story_label: "Story",
      experience_mapping_scene_label: "Scene",
      experience_mapping_action_label: "Action",
      experience_mapping_field_title: "Title",
      experience_mapping_field_description: "Description",
      experience_mapping_field_genre: "Genre",
      experience_mapping_field_content_rating: "Content rating",
      experience_mapping_field_color: "Color",
      experience_mapping_field_name: "Name",
      experience_mapping_field_type: "Type",
      experience_mapping_field_order: "Order",
      experience_mapping_field_duration: "Duration",
      experience_mapping_field_properties: "Properties",
      experience_mapping_field_subproperties: "Subproperties",
      experience_mapping_save_changes: "Save changes",
      experience_mapping_saved: "Saved",
      experience_mapping_save_error: "Could not save changes.",
      experience_mapping_delete_story: "Delete story",
      experience_mapping_delete_scene: "Delete scene",
      experience_mapping_delete_action: "Delete action",
      experience_mapping_delete_confirm: "Click again to confirm",
      experience_mapping_delete_error: "Delete failed.",
      experience_mapping_expand_all: "Expand all",
      experience_mapping_collapse_all: "Collapse all",
      experience_mapping_forbidden: "You do not have admin access for this section.",
      experience_mapping_bad_json: "JSON must be valid before saving.",
      experience_mapping_intro:
        "Edit realm vocabulary from largest to smallest. Generate JSON and paste it in chat for code application.",
      experience_mapping_dirty: "dirty changes",
      experience_mapping_export_ready: "No unsaved mapping edits yet.",
      experience_mapping_export_json: "Generate JSON export",
      experience_mapping_copy_json: "Copy JSON",
      experience_mapping_copied: "Copied",
      experience_mapping_paste_instruction:
        "Paste this JSON in chat and I will apply it to chuzi-shared.",
      experience_mapping_export_empty: "Export output appears here.",
      experience_mapping_select_realm: "Select realm",
      experience_mapping_group_major_idea: "Major Idea",
      experience_mapping_helper_realm_idea:
        "Highest-level concept for this realm.",
      experience_mapping_save_experience: "Save to experience",
      experience_mapping_saved_experience:
        "Saved to current experience. Some labels appear immediately.",
      experience_mapping_group_experience_root: "Experience Root",
      experience_mapping_group_node_types: "Node Types",
      experience_mapping_group_scene_structure: "Scene Structure",
      experience_mapping_group_media: "Media Terms",
      experience_mapping_group_counts: "Counts and Adjacent Labels",
      experience_mapping_helper_story: "Largest narrative unit.",
      experience_mapping_helper_scene: "Contained unit under story.",
      experience_mapping_helper_scene_choice: "Branching choice in a scene.",
      experience_mapping_helper_node: "Smallest flow node.",
      experience_mapping_helper_alt_media: "Smallest related media label.",
    },
    locales: {
      es: {
        genre: "Galaxia",
        story: "Sistema Estelar",
        scene: "Planeta",
        scene_choice: "Trayectoria",
        player: "Viajero",
        library: "Carta Estelar",
        editor: "Control de Misión",
        publish: "Lanzar",
        the_end: "Órbita Final",
        untitled_story: "Sistema Estelar sin título",
        menu_create_story: "Nuevo sistema estelar",
        film_title_placeholder: "Título del sistema estelar",
        select_genre: "Seleccionar galaxia",
        created_by: "Dirigido por",
      },
      fr: {
        genre: "Galaxie",
        story: "Système Stellaire",
        scene: "Planète",
        scene_choice: "Trajectoire",
        player: "Voyageur",
        library: "Carte Stellaire",
        editor: "Contrôle de Mission",
        publish: "Lancer",
        the_end: "Orbite Finale",
        untitled_story: "Système stellaire sans titre",
        menu_create_story: "Nouveau système stellaire",
        film_title_placeholder: "Titre du système stellaire",
        select_genre: "Sélectionner une galaxie",
        created_by: "Réalisé par",
      },
      de: {
        genre: "Galaxie",
        story: "Sternsystem",
        scene: "Planet",
        player: "Reisender",
        publish: "Starten",
      },
      pt: {
        genre: "Galáxia",
        story: "Sistema Estelar",
        scene: "Planeta",
        player: "Viajante",
        publish: "Lançar",
      },
    },
  },
  wilds: {
    label: "CHUZI WILDS",
    short_label: "Wilds",
    lexicon: {
      genre: "Biome",
      story: "Grove",
      scene: "Clearing",
      scene_choice: "Trail",
      node: "Seed",
      node_type_choice: "Trail",
      node_type_media: "Bloom",
      node_type_go_to_scene: "Crossing",
      player: "Wanderer",
      library: "Canopy",
      library_open: "Open Canopy",
      library_close: "Close Canopy",
      editor: "Heartwood",
      publish: "Plant",
      experience_realm_idea: "Untamed Nature",
      the_end: "Roots",
      media_pool: "Undergrowth",
      scene_graph: "Canopy",
      watch_path: "Your trail",
      untitled_story: "Untitled Grove",
      unknown_genre: "Unknown Biome",
      scenes_count: "clearings",
      choices_count: "trails",
      drafts_published: "Drafts + Planted",
      published_ver: "Planted ver.",
      draft: "Draft",
      no_scenes_yet: "No clearings in this canopy yet.",
      no_path_yet: "No trail to show yet.",
      menu_empty_drafts: "No groves yet. Plant one to begin.",
      menu_empty_published: "No planted groves in the canopy.",
      menu_published_heading: "Planted groves",
      menu_create_story: "New grove",
      menu_create_film: "Create film",
      film_title_placeholder: "Grove title",
      select_genre: "Select biome",
      genre_field_aria: "Biome",
      delete_story_verb: "Delete grove",
      title_scene_default: "Title clearing",
      choices_made_stat: "trails taken",
      content_rating: "Field Guide",
      content_rating_field_aria: "Field guide",
      select_content_rating: "Select field guide",
      unrated: "Unmarked",
      viewer_credits: "Sap",
      creator_credits: "Pollen",
      editor_media_upload: "Upload Bloom",
      editor_media_preview: "Bloom Preview",
      editor_alt_media: "Additional Media",
      editor_choices: "Choices",
      editor_scene_settings: "Clearing Settings",
      editor_title_scene: "Title Clearing",
      editor_ending_scene: "Roots",
      editor_play: "Unfurl",
      editor_pause: "Rest",
      editor_prev_frame: "Previous Frame",
      editor_next_frame: "Next Frame",
      editor_seek: "Seek",
      editor_no_media: "No bloom assigned",
      editor_uploading: "Blooming\u2026",
      editor_drop_media: "Drop bloom here",
      editor_scene_type: "Clearing Type",
      editor_save: "Engrave",
      editor_cancel: "Cancel",
      editor_create_scene: "Plant Clearing",
      editor_create_scene_plain: "Create New Scene",
      editor_create_scene_cost: "1 Pollen",
      editor_delete_scene_cta: "Delete Scene",
      editor_delete_scene_confirm: "Click again to confirm",
      editor_scene_locked_delete: "Title and end scenes cannot be deleted.",
      editor_scene_color: "Clearing Tint",
      editor_ai_generate: "Grow Bloom",
      editor_ai_generating: "Seed Sprouting\u2026",
      editor_ai_mood_question: "What feeling should this clearing evoke?",
      editor_ai_style_question: "What growth pattern for this bloom?",
      editor_ai_prompt_question: "Describe this clearing",
      editor_ai_accept: "Root Bloom",
      editor_ai_reject: "Prune Bloom",
      editor_ai_retry: "Regrow",
      editor_ai_feedback_prompt: "How should we reshape the growth?",
      editor_ai_credit_cost: "1 Pollen per bloom",
      editor_ai_generating_scene: "Clearing emerging\u2026",
      editor_ai_style_badge: "Growth Style",
      editor_ai_failed: "Growth withered. Try regrowing.",
      editor_media_attached: "This clearing already has a bloom rooted.",
      editor_remove_media: "Uproot Bloom",
      editor_media_question: "What's this scene's media?",
      editor_media_type_text: "Text",
      editor_media_type_imagery: "Imagery",
      editor_media_type_film: "Film",
      editor_media_preview_cta: "Preview",
      editor_media_preview_disabled: "Add text to enable preview.",
      editor_text_toolbar_label: "Generator",
      editor_text_font_label: "Font",
      editor_text_color_label: "Text Color",
      editor_text_background_label: "Background",
      editor_text_placeholder: "Start writing scene media...",
      editor_media_placeholder_imagery: "Imagery authoring is coming soon.",
      editor_media_placeholder_film: "Film authoring is coming soon.",
      constellation_no_coverbox: "Unseen",
      hud_edit_control: "Tend",
      hud_delete_control: "Uproot",
      hud_publish_control: "Plant",
      create_button: "CREATE",
      publish_form_heading: "Planting check",
      tags_label: "Root Tags",
      tags_placeholder: "Search root tags\u2026",
      tags_empty: "No root tags yet",
      story_picker_label: "Groves",
      created_by: "Tended by",
      director_profile_title: "Director profile",
      director_profile_name_label: "Name",
      director_profile_realm_label: "Experience realm",
      director_profile_image_label: "Image",
      director_profile_image_hint:
        "Realm-themed seal — switching the realm above swaps the seal. Custom uploads land with the V1 avatar endpoints.",
      director_profile_tab_profile: "Profile",
      director_profile_tab_experience_mapping: "Experience Mapping",
      director_profile_admin_only: "Admin only",
      director_profile_cancel: "Cancel",
      director_profile_save: "Save",
      director_profile_saving: "Saving…",
      director_profile_name_required: "Name is required.",
      director_profile_save_failed: "Save failed",
      experience_mapping_loading: "Loading experience mapping…",
      experience_mapping_empty: "No template hierarchy available yet.",
      experience_mapping_retry: "Retry",
      experience_mapping_story_label: "Story",
      experience_mapping_scene_label: "Scene",
      experience_mapping_action_label: "Action",
      experience_mapping_field_title: "Title",
      experience_mapping_field_description: "Description",
      experience_mapping_field_genre: "Genre",
      experience_mapping_field_content_rating: "Content rating",
      experience_mapping_field_color: "Color",
      experience_mapping_field_name: "Name",
      experience_mapping_field_type: "Type",
      experience_mapping_field_order: "Order",
      experience_mapping_field_duration: "Duration",
      experience_mapping_field_properties: "Properties",
      experience_mapping_field_subproperties: "Subproperties",
      experience_mapping_save_changes: "Save changes",
      experience_mapping_saved: "Saved",
      experience_mapping_save_error: "Could not save changes.",
      experience_mapping_delete_story: "Delete story",
      experience_mapping_delete_scene: "Delete scene",
      experience_mapping_delete_action: "Delete action",
      experience_mapping_delete_confirm: "Click again to confirm",
      experience_mapping_delete_error: "Delete failed.",
      experience_mapping_expand_all: "Expand all",
      experience_mapping_collapse_all: "Collapse all",
      experience_mapping_forbidden: "You do not have admin access for this section.",
      experience_mapping_bad_json: "JSON must be valid before saving.",
      experience_mapping_intro:
        "Edit realm vocabulary from largest to smallest. Generate JSON and paste it in chat for code application.",
      experience_mapping_dirty: "dirty changes",
      experience_mapping_export_ready: "No unsaved mapping edits yet.",
      experience_mapping_export_json: "Generate JSON export",
      experience_mapping_copy_json: "Copy JSON",
      experience_mapping_copied: "Copied",
      experience_mapping_paste_instruction:
        "Paste this JSON in chat and I will apply it to chuzi-shared.",
      experience_mapping_export_empty: "Export output appears here.",
      experience_mapping_select_realm: "Select realm",
      experience_mapping_group_major_idea: "Major Idea",
      experience_mapping_helper_realm_idea:
        "Highest-level concept for this realm.",
      experience_mapping_save_experience: "Save to experience",
      experience_mapping_saved_experience:
        "Saved to current experience. Some labels appear immediately.",
      experience_mapping_group_experience_root: "Experience Root",
      experience_mapping_group_node_types: "Node Types",
      experience_mapping_group_scene_structure: "Scene Structure",
      experience_mapping_group_media: "Media Terms",
      experience_mapping_group_counts: "Counts and Adjacent Labels",
      experience_mapping_helper_story: "Largest narrative unit.",
      experience_mapping_helper_scene: "Contained unit under story.",
      experience_mapping_helper_scene_choice: "Branching choice in a scene.",
      experience_mapping_helper_node: "Smallest flow node.",
      experience_mapping_helper_alt_media: "Smallest related media label.",
    },
    locales: {
      es: {
        genre: "Bioma",
        story: "Arboleda",
        scene: "Claro",
        scene_choice: "Sendero",
        player: "Errante",
        library: "Dosel",
        editor: "Duramen",
        publish: "Plantar",
        the_end: "Raíces",
        untitled_story: "Arboleda sin título",
        menu_create_story: "Nueva arboleda",
        film_title_placeholder: "Título de la arboleda",
        select_genre: "Seleccionar bioma",
        created_by: "Cuidado por",
      },
      fr: {
        genre: "Biome",
        story: "Bosquet",
        scene: "Clairière",
        scene_choice: "Sentier",
        player: "Vagabond",
        library: "Canopée",
        editor: "Cœur de bois",
        publish: "Planter",
        the_end: "Racines",
        untitled_story: "Bosquet sans titre",
        menu_create_story: "Nouveau bosquet",
        film_title_placeholder: "Titre du bosquet",
        select_genre: "Sélectionner un biome",
        created_by: "Soigné par",
      },
      de: {
        genre: "Biom",
        story: "Hain",
        scene: "Lichtung",
        player: "Wanderer",
        publish: "Pflanzen",
      },
      pt: {
        genre: "Bioma",
        story: "Bosque",
        scene: "Clareira",
        player: "Andarilho",
        publish: "Plantar",
      },
    },
  },
};

export const FALLBACK_LEXICON: Record<string, string> = {
  genre: "Genre",
  story: "Story",
  scene: "Scene",
  scene_choice: "Choice",
  node: "Node",
  node_type_choice: "Choice",
  node_type_media: "Media",
  node_type_go_to_scene: "Go to scene",
  player: "Player",
  library: "Library",
  library_open: "Open scene tree",
  library_close: "Close scene tree",
  editor: "Editor",
  publish: "Publish",
  experience_realm_idea: "Experience Theme",
  the_end: "The End",
  media_pool: "Media Pool",
  scene_graph: "Scene tree",
  watch_path: "Your path",
  untitled_story: "Untitled Story",
  unknown_genre: "Unknown Genre",
  scenes_count: "scenes",
  choices_count: "choices",
  drafts_published: "Drafts + Published",
  published_ver: "Published ver.",
  draft: "Draft",
  no_scenes_yet: "No scenes available yet.",
  no_path_yet: "No path to show yet.",
  menu_empty_drafts: "No films yet. Create one to get started.",
  menu_empty_published: "No published films found.",
  menu_published_heading: "Published Films",
  menu_create_story: "Create Story",
  menu_create_film: "Create Film",
  film_title_placeholder: "Film title",
  select_genre: "Select genre",
  genre_field_aria: "Film genre",
  delete_story_verb: "Delete film",
  title_scene_default: "Title Scene",
  choices_made_stat: "choices made",
  content_rating: "Rating",
  content_rating_field_aria: "Content rating",
  select_content_rating: "Select rating",
  unrated: "Not Rated",
  viewer_credits: "Viewer Credits",
  creator_credits: "Creator Credits",
  editor_media_upload: "Upload Media",
  editor_media_preview: "Media Preview",
  editor_alt_media: "Additional Media",
  editor_choices: "Choices",
  editor_scene_settings: "Scene Settings",
  editor_title_scene: "Title Scene",
  editor_ending_scene: "Ending Scene",
  editor_play: "Play",
  editor_pause: "Pause",
  editor_prev_frame: "Previous Frame",
  editor_next_frame: "Next Frame",
  editor_seek: "Seek",
  editor_no_media: "No media assigned",
  editor_uploading: "Uploading\u2026",
  editor_drop_media: "Drop media here",
  editor_scene_type: "Scene Type",
  editor_save: "Save",
  editor_cancel: "Cancel",
  editor_create_scene: "Create Scene",
  editor_create_scene_plain: "Create New Scene",
  editor_create_scene_cost: "1 credit",
  editor_delete_scene_cta: "Delete Scene",
  editor_delete_scene_confirm: "Click again to confirm",
  editor_scene_locked_delete: "Title and end scenes cannot be deleted.",
  editor_scene_color: "Scene Color",
  editor_ai_generate: "Generate with AI",
  editor_ai_generating: "Generating\u2026",
  editor_ai_mood_question: "What mood should this scene convey?",
  editor_ai_style_question: "What visual style do you want?",
  editor_ai_prompt_question: "Describe this scene",
  editor_ai_accept: "Accept",
  editor_ai_reject: "Reject",
  editor_ai_retry: "Try Again",
  editor_ai_feedback_prompt: "What should we change?",
  editor_ai_credit_cost: "1 credit per generation",
  editor_ai_generating_scene: "Scene generating\u2026",
  editor_ai_style_badge: "Style",
  editor_ai_failed: "Generation failed. Please try again.",
  editor_media_attached: "This scene already has media attached.",
  editor_remove_media: "Remove Media",
  editor_media_question: "What's this scene's media?",
  editor_media_type_text: "Text",
  editor_media_type_imagery: "Imagery",
  editor_media_type_film: "Film",
  editor_media_preview_cta: "Preview",
  editor_media_preview_disabled: "Add text to enable preview.",
  editor_text_toolbar_label: "Generator",
  editor_text_font_label: "Font",
  editor_text_color_label: "Text Color",
  editor_text_background_label: "Background",
  editor_text_placeholder: "Start writing scene media...",
  editor_media_placeholder_imagery: "Imagery authoring is coming soon.",
  editor_media_placeholder_film: "Film authoring is coming soon.",
  constellation_no_coverbox: "No cover",
  hud_edit_control: "Edit",
  hud_delete_control: "Delete",
  hud_publish_control: "Publish",
  create_button: "CREATE",
  publish_form_heading: "Publish checklist",
  tags_label: "Tags",
  tags_placeholder: "Search tags\u2026",
  tags_empty: "No tags yet",
  story_picker_label: "Stories",
  created_by: "Created by",
  director_profile_title: "Director profile",
  director_profile_name_label: "Name",
  director_profile_realm_label: "Experience realm",
  director_profile_image_label: "Image",
  director_profile_image_hint:
    "Realm-themed seal — switching the realm above swaps the seal. Custom uploads land with the V1 avatar endpoints.",
  director_profile_tab_profile: "Profile",
  director_profile_tab_experience_mapping: "Experience Mapping",
  director_profile_admin_only: "Admin only",
  director_profile_cancel: "Cancel",
  director_profile_save: "Save",
  director_profile_saving: "Saving…",
  director_profile_name_required: "Name is required.",
  director_profile_save_failed: "Save failed",
  experience_mapping_loading: "Loading experience mapping…",
  experience_mapping_empty: "No template hierarchy available yet.",
  experience_mapping_retry: "Retry",
  experience_mapping_story_label: "Story",
  experience_mapping_scene_label: "Scene",
  experience_mapping_action_label: "Action",
  experience_mapping_field_title: "Title",
  experience_mapping_field_description: "Description",
  experience_mapping_field_genre: "Genre",
  experience_mapping_field_content_rating: "Content rating",
  experience_mapping_field_color: "Color",
  experience_mapping_field_name: "Name",
  experience_mapping_field_type: "Type",
  experience_mapping_field_order: "Order",
  experience_mapping_field_duration: "Duration",
  experience_mapping_field_properties: "Properties",
  experience_mapping_field_subproperties: "Subproperties",
  experience_mapping_save_changes: "Save changes",
  experience_mapping_saved: "Saved",
  experience_mapping_save_error: "Could not save changes.",
  experience_mapping_delete_story: "Delete story",
  experience_mapping_delete_scene: "Delete scene",
  experience_mapping_delete_action: "Delete action",
  experience_mapping_delete_confirm: "Click again to confirm",
  experience_mapping_delete_error: "Delete failed.",
  experience_mapping_expand_all: "Expand all",
  experience_mapping_collapse_all: "Collapse all",
  experience_mapping_forbidden: "You do not have admin access for this section.",
  experience_mapping_bad_json: "JSON must be valid before saving.",
  experience_mapping_intro:
    "Edit realm vocabulary from largest to smallest. Generate JSON and paste it in chat for code application.",
  experience_mapping_dirty: "dirty changes",
  experience_mapping_export_ready: "No unsaved mapping edits yet.",
  experience_mapping_export_json: "Generate JSON export",
  experience_mapping_copy_json: "Copy JSON",
  experience_mapping_copied: "Copied",
  experience_mapping_paste_instruction:
    "Paste this JSON in chat and I will apply it to chuzi-shared.",
  experience_mapping_export_empty: "Export output appears here.",
  experience_mapping_select_realm: "Select realm",
  experience_mapping_group_major_idea: "Major Idea",
  experience_mapping_helper_realm_idea:
    "Highest-level concept for this realm.",
  experience_mapping_save_experience: "Save to experience",
  experience_mapping_saved_experience:
    "Saved to current experience. Some labels appear immediately.",
  experience_mapping_group_experience_root: "Experience Root",
  experience_mapping_group_node_types: "Node Types",
  experience_mapping_group_scene_structure: "Scene Structure",
  experience_mapping_group_media: "Media Terms",
  experience_mapping_group_counts: "Counts and Adjacent Labels",
  experience_mapping_helper_story: "Largest narrative unit.",
  experience_mapping_helper_scene: "Contained unit under story.",
  experience_mapping_helper_scene_choice: "Branching choice in a scene.",
  experience_mapping_helper_node: "Smallest flow node.",
  experience_mapping_helper_alt_media: "Smallest related media label.",
};

/**
 * Per-locale overrides for FALLBACK_LEXICON. Missing keys fall through to
 * the English fallback. Mirrors PHP `chuzi_realms.fallback_locales`.
 */
export const FALLBACK_LOCALES: Partial<
  Record<LocaleId, Record<string, string>>
> = {
  es: {
    genre: "Género",
    story: "Historia",
    scene: "Escena",
    scene_choice: "Elección",
    player: "Reproductor",
    library: "Biblioteca",
    editor: "Editor",
    publish: "Publicar",
    the_end: "Fin",
    untitled_story: "Historia sin título",
    menu_create_story: "Crear historia",
    menu_create_film: "Crear película",
    film_title_placeholder: "Título de la película",
    select_genre: "Seleccionar género",
    delete_story_verb: "Eliminar película",
    created_by: "Creado por",
  },
  fr: {
    genre: "Genre",
    story: "Histoire",
    scene: "Scène",
    scene_choice: "Choix",
    player: "Lecteur",
    library: "Bibliothèque",
    editor: "Éditeur",
    publish: "Publier",
    the_end: "Fin",
    untitled_story: "Histoire sans titre",
    menu_create_story: "Créer une histoire",
    menu_create_film: "Créer un film",
    film_title_placeholder: "Titre du film",
    select_genre: "Sélectionner un genre",
    delete_story_verb: "Supprimer le film",
    created_by: "Créé par",
  },
  de: {
    genre: "Genre",
    story: "Geschichte",
    scene: "Szene",
    publish: "Veröffentlichen",
    the_end: "Ende",
    untitled_story: "Unbenannte Geschichte",
    menu_create_story: "Geschichte erstellen",
    film_title_placeholder: "Filmtitel",
    select_genre: "Genre auswählen",
    created_by: "Erstellt von",
  },
  pt: {
    genre: "Gênero",
    story: "História",
    scene: "Cena",
    publish: "Publicar",
    the_end: "Fim",
    untitled_story: "História sem título",
    menu_create_story: "Criar história",
    film_title_placeholder: "Título do filme",
    select_genre: "Selecionar gênero",
    created_by: "Criado por",
  },
};

function resolveFallback(locale: LocaleId | null | undefined): Record<string, string> {
  const overrides = locale && FALLBACK_LOCALES[locale];
  return overrides ? { ...FALLBACK_LEXICON, ...overrides } : { ...FALLBACK_LEXICON };
}

function resolveRealm(
  realmId: RealmId,
  locale: LocaleId | null | undefined
): Record<string, string> {
  const realm = REALMS[realmId];
  const overrides = locale && realm.locales ? realm.locales[locale] : undefined;
  const runtimeOverrides = runtimeRealmLexiconOverrides[realmId];
  return {
    ...realm.lexicon,
    ...(overrides ?? {}),
    ...(runtimeOverrides ?? {}),
  };
}

/**
 * Get a lexicon value for a realm + locale, falling back to the neutral
 * lexicon (which itself respects locale).
 */
export function t(
  realmId: RealmId | null | undefined,
  key: string,
  fallback = "",
  locale: LocaleId | null | undefined = null
): string {
  if (realmId && REALMS[realmId]) {
    const realmLex = resolveRealm(realmId, locale);
    if (realmLex[key] !== undefined) return realmLex[key];
  }
  const fb = resolveFallback(locale);
  return fb[key] ?? fallback;
}

/**
 * Get the full merged lexicon for a realm + locale (realm lexicon on top of
 * locale-aware fallback).
 */
export function lexiconForRealm(
  realmId: RealmId | null | undefined,
  locale: LocaleId | null | undefined = null
): Record<string, string> {
  const fb = resolveFallback(locale);
  if (!realmId || !REALMS[realmId]) {
    return fb;
  }
  return { ...fb, ...resolveRealm(realmId, locale) };
}
